name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ruff linter
      run: |
        ruff check
  
    - name: Run ruff formatter
      run: |
        ruff format --check --diff

    - name: Run mypy
      run: |
        mypy .