name: Specification by Example Tests

on:
  push:
  workflow_dispatch:

jobs:
  pytest-bdd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        playwright install --with-deps

    - name: Run Specification by Example tests
      run: |
        pytest

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
          name: cucumber-report
          path: cucumber-report/